apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-app
spec:
  selector:
    matchLabels:
      app: users-app
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: users-app
    spec:
      containers:
      - name: users-app
        image: asia-southeast1-docker.pkg.dev/arthetic/arthetic-images/users-svc:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: users-secret
                key: database_url
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: users-secret
                key: jwt_secret
          - name: JWT_EXPIRES_IN
            valueFrom:
              secretKeyRef:
                name: users-secret
                key: jwt_expires_in
          - name: SALT_ROUNDS
            valueFrom:
              secretKeyRef:
                name: users-secret
                key: salt_rounds
          - name: PORT
            value: "4000"
